project:
  name: bachelor_thesis_pipeline
  debug: true

network:
  orchestrator_url: http://orchestrator:8000
  rc_cube_service_url: http://rc_cube:8000
  sam_service_url: http://sam:8000
  contact_graspnet_service_url: http://contactgraspnet:8000
  llm_service_url: http://llm:8000

paths:
  output_debug: /shared/debug
  pipeline_file_share: /shared/pipeline_io

pipeline:
  mock_rc_cube_cam: false
  mock_rc_cube_full: true
  use_obj_selection: true

rc_cube:
  output_npz: /shared/pipeline_io/rc_cube_pointcloud.npz
  output_left_img: /shared/pipeline_io/left.png
  rc_mock_cam_input: /shared/debug/rc_cube/rc_cube_mock_cam_output
  rc_mock_full_input: /shared/debug/rc_cube/rc_cube_mock_full_output/output_2026-04-05_15-45-32.npz
  timeout_sec: 5.0
  max_message_size_mb: 300
  left_enabled: true
  right_enabled: false
  disparity_enabled: true
  disparity_error_enabled: false
  confidence_enabled: true
  mesh_enabled: false
  color: true
  conf_threshhold: 128

sam:
  device: cuda
  checkpoint: /app/checkpoints/sam2.1_l.pt
  output_npz: /shared/pipeline_io/sam_segmented_output.npz
  output_png: /shared/pipeline_io/sam_segmented_output.png
  min_area: 100
  max_area_ratio: 0.5

contact_graspnet:
  checkpoint_dir: /app/contact_graspnet/contact_graspnet/checkpoints/scene_test_2048_bs3_hor_sigma_001
  output_png: /shared/pipeline_io/cgn_annotated_output.png
  heatmap_dir: /shared/debug/cgn/heatmap

  prediction:
    z_min: 0.0
    z_max: 2.0
    filter_grasps: true
    local_regions: true
    forward_passes: 1
    skip_border_objects: True
    margin_px: 5
    segmap_id: 4 # Gets used only when object selection is skipped (use_obj_selection: false)

  selection:
    num_grasps: 4
    top_score_candidates: 10
    gripper_width: 0.16

    dbscan_clustering: true # otherwise num_grasps top score candidates are selected 
    dbscan:
      min_score: 0.5          # filter weak grasps first
      eps: 1.4                # cluster radius (after normalization)
      min_samples: 1          # keep small clusters
      orientation_weight: 0.3 # balance position vs orientation

  gripper_projection:
    draw_grip_opening_bigger: true
    increase_grip_opening_by: 0.00
    gripper_line_width: 1
    number_line_width: 1

  camera:
    fallback_fx: 525.0
    fallback_fy: 525.0
    fallback_cx: null
    fallback_cy: null

llm:
  max_completion_tokens: 1000
  prompt_path: /app/llm/prompts.yaml
  schema_path: /app/llm/schemas

