project:
  name: bachelor_thesis_pipeline
  debug: true

network:
  orchestrator_url: http://orchestrator:8000
  rc_cube_service_url: http://rc_cube:8000
  uois_service_url: http://uois:8000
  contact_graspnet_service_url: http://contactgraspnet:8000
  llm_service_url: http://llm:8000

paths:
  output_debug: /shared/debug
  pipeline_file_share: /shared/pipeline_io

rc_cube:
  ip: 172.27.48.156:50051
  timeout_sec: 25.0
  max_message_size_mb: 300
  

uois:
  img_numbers_to_save: [0, 1, 2, 3, 4] # Image numbers to save for debugging [0, 4]
  checkpoint_dir: /app/uois/checkpoints

  dsn_config:
    feature_dim: 64
    max_GMS_iters: 10
    num_seeds: 400
    epsilon: 0.10
    sigma: 0.04
    subsample_factor: 5
    min_pixels_thresh: 500
    tau: 15.0 

  rrn_config:
    feature_dim: 64
    img_H: 224
    img_W: 224
    use_coordconv: false

  uois3d_config:
    padding_percentage: 0.25
    use_open_close_morphology: true
    open_close_morphology_ksize: 9
    use_largest_connected_component: false

  checkpoints:
    dsn: DepthSeedingNetwork_3D_TOD_checkpoint.pth
    rrn: RRN_OID_checkpoint.pth

contact_graspnet:
  checkpoint_dir: /app/contact_graspnet/contact_graspnet/checkpoints/scene_test_2048_bs3_hor_sigma_001

  prediction:
    z_min: 0.0
    z_max: 5.1
    filter_grasps: true
    local_regions: true
    forward_passes: 1
    segmap_id: 4

  selection:
    num_grasps: 5
    top_score_candidates: 20
    distance_div_filtering: false
    gripper_width: 0.08

  gripper_projection:
    use_default_opening: true
    default_opening: 0.050
    draw_confidence: false

  camera:
    fallback_fx: 525.0
    fallback_fy: 525.0
    fallback_cx: null
    fallback_cy: null

llm:
  deployment: gpt-5.3-chat-global-standard
  max_completion_tokens: 1000

pipeline:
  use_rc_cube: true
  run_uois: true
  run_contact_graspnet: true
  run_llm: true